import { db } from "../../../db";
import { jobs, users_profile, skills, experience, education, certifications } from "../../../db/schema";
import { eq } from "drizzle-orm";
import fs from "fs";
import path from "path";

export class PromptOrchestrator {
  private async getCompleteProfile(userId: string) {
    const [profile] = await db.select().from(users_profile).where(eq(users_profile.user_id, userId));
    if (!profile) throw new Error("Profile not found");

    const [userSkills, userExp, userEdu, userCerts] = await Promise.all([
      db.select().from(skills).where(eq(skills.profile_id, profile.id)),
      db.select().from(experience).where(eq(experience.profile_id, profile.id)),
      db.select().from(education).where(eq(education.profile_id, profile.id)),
      db.select().from(certifications).where(eq(certifications.profile_id, profile.id))
    ]);

    return { ...profile, skills: userSkills, experience: userExp, education: userEdu, certs: userCerts };
  }

  private async getJob(jobId: string) {
    const [job] = await db.select().from(jobs).where(eq(jobs.id, jobId));
    return job;
  }

  static getProfileLevel(profile: any): string {
    const hasEdu = profile.education?.length > 0;
    const hasSkills = profile.skills?.length > 0;
    const hasCerts = profile.certs?.length > 0;
    const hasExp = profile.experience?.length > 0;

    if (hasExp && hasSkills && hasEdu) return "LEVEL_4_MASTER";
    if (hasExp && (hasSkills || hasEdu)) return "LEVEL_3_PROFESSIONAL";
    if (hasSkills || hasEdu || hasCerts) return "LEVEL_2_RISING";
    return "LEVEL_1_NEWBIE";
  }

  async generateMasterPrompt(userId: string, jobId: string) {
    const userProfile = await this.getCompleteProfile(userId);
    const job = await this.getJob(jobId);
    if (!job) throw new Error("Job not found");

    const levelKey = PromptOrchestrator.getProfileLevel(userProfile);

    // 1. Load the "Brain" (The JSON generated by the AI teacher)
    const brainPath = path.join(process.cwd(), "src/lib/promptGenerator.json");
    if (!fs.existsSync(brainPath)) {
      throw new Error("Brain not found. Please run the build-brain script first.");
    }

    const brain = JSON.parse(fs.readFileSync(brainPath, "utf-8"));
    const specializedStrategy = brain[levelKey];

    // 2. Build the "Prompt for the Generator"
    // We pass the specific strategy instructions + the actual data
    return `
      # SYSTEM STRATEGY FOR ${levelKey}:
      ${specializedStrategy}

      # CONTEXTUAL DATA:
      ## CANDIDATE:
      ${JSON.stringify(userProfile)}

      ## JOB POSTING:
      ${JSON.stringify(job)}

      # YOUR TASK:
      Acting as the prompt engineer, combine the strategy above with the data provided to output a FINAL SYSTEM PROMPT. 
      This system prompt will be used to generate a winning proposal for the candidate.
      OUTPUT ONLY THE PROMPT TEXT.
    `;
  }
}